name: PyPI Test Upload

on:
 push:
  tags: 
    - v*

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      fail-fast: true 
      python-version: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        python -m pipenv install --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        python -m pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pipenv run pytest . --cov=pepino --cov-report=xml --doctest-modules --junitxml=pytest.xml
    - name: Build wheel
      run: |
        python -m pipenv run python setup.py bdist_wheel
    - name: Upload Package to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with: 
        password: ${{ secrets.TEST_PYPI }}
        repository_url: https://test.pypi.org/legacy/